# Generated by Django 3.2.3 on 2021-06-05 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='vin_nubmer',
            new_name='vin_number',
        ),
    ]
