# Generated by Django 3.2.3 on 2021-06-19 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_auto_20210619_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['car_model']},
        ),
    ]
