# Generated by Django 3.2.4 on 2021-06-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_auto_20210621_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='made_date',
            field=models.DateField(),
        ),
    ]
