# Generated by Django 3.2.4 on 2021-06-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_alter_car_made_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='made_date',
            field=models.DateField(default='yyyy-mm-dd'),
        ),
    ]
