# Generated by Django 3.2.4 on 2021-07-19 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0012_alter_company_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['carmodel']},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ['company']},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.RenameField(
            model_name='car',
            old_name='car_model',
            new_name='carmodel',
        ),
    ]
